const url = 'http://www.kxhome.xyz:8085/ex0/images/';

const parameter = {
    sun: {
        radius: 100,
        texture: url + 'sun.jpg',
    },
    mercury: {
        radius: 5,
        orbitRadius: 200,
        revolution: 41,
        rotation: 620,
        startAngle : 1000,
        texture: url + 'mercury.jpg',
    },
    venus: {
        radius: 12,
        orbitRadius: 300,
        revolution: 16,
        rotation: -180,
        startAngle : 2000,
        texture: url + 'venus.jpg',
    },
    moon: {
        radius: 3,
        orbitRadius: 30,
        revolution: 30,
        rotation: 10,
        startAngle : 0,
        texture: url + 'moon.jpg',
    },
    earth: {
        radius: 12,
        orbitRadius: 400,
        revolution: 10,
        rotation: 360,
        startAngle : 3000,
        texture: url + 'earth.jpg',
    },
    mars: {
        radius: 7,
        orbitRadius: 500,
        revolution: 8,
        rotation: 370,
        startAngle : 4000,
        texture: url + 'mars.jpg',
    },
    jupiter: {
        radius: 50,
        orbitRadius: 600,
        revolution: 5,
        rotation: 120,
        startAngle : 5000,
        texture: url + 'jupiter.jpg',
    },
    saturn: {
        radius: 48,
        orbitRadius: 700,
        revolution: 4.5,
        rotation: 150,
        startAngle : 6000,
        texture: url + 'saturn.jpg',
    },
    uranus: {
        radius: 26,
        orbitRadius: 800,
        revolution: 6,
        rotation: -110,
        startAngle : 7000,
        texture: url + 'uranus.jpg',
    },
    neptune: {
        radius: 24,
        orbitRadius: 900,
        revolution: 5.5,
        rotation: 100,
        startAngle : 8000,
        texture: url + 'neptune.jpg',
    }
}
